import type { ModuleInstance } from './main.js'

export function UpdateVariableDefinitions(self: ModuleInstance): void {
	self.setVariableDefinitions([
		{ variableId: 'connection_status', name: 'Connection status' },
		{ variableId: 'websocket_connected', name: 'WebSocket connected' },
		{ variableId: 'server_url', name: 'Server URL' },
		{ variableId: 'display_mode', name: 'Display mode' },
		{ variableId: 'display_time_source', name: 'Current display time source' },
		{ variableId: 'display_time_formatted', name: 'Current display time formatted' },
		{ variableId: 'display_time_full_formatted', name: 'Current display time full formatted' },
		{ variableId: 'display_time_hours', name: 'Current display time hours' },
		{ variableId: 'display_time_minutes', name: 'Current display time minutes' },
		{ variableId: 'display_time_seconds', name: 'Current display time seconds' },
		{ variableId: 'timer_running', name: 'Timer running' },
		{ variableId: 'timer_full_formatted', name: 'Timer remaining full formatted' },
		{ variableId: 'timer_blink_enabled', name: 'Timer blink enabled' },
		{ variableId: 'timer_blink_active', name: 'Timer blink active state' },
		{ variableId: 'timer_hours', name: 'Timer remaining hours' },
		{ variableId: 'timer_minutes', name: 'Timer remaining minutes' },
		{ variableId: 'timer_seconds', name: 'Timer remaining seconds' },
		{ variableId: 'duration_seconds', name: 'Timer duration in seconds' },
		{ variableId: 'duration_formatted', name: 'Timer duration formatted' },
		{ variableId: 'duration_full_formatted', name: 'Timer duration full formatted' },
		{ variableId: 'duration_hours', name: 'Timer duration hours' },
		{ variableId: 'duration_minutes', name: 'Timer duration minutes' },
		{ variableId: 'duration_seconds_component', name: 'Timer duration seconds component' },
		{ variableId: 'time_remaining_seconds', name: 'Time remaining in seconds' },
		{ variableId: 'time_remaining_formatted', name: 'Time remaining formatted' },
		{ variableId: 'elapsed_seconds', name: 'Elapsed time in seconds' },
		{ variableId: 'elapsed_formatted', name: 'Elapsed time formatted' },
		{ variableId: 'elapsed_full_formatted', name: 'Elapsed time full formatted' },
		{ variableId: 'elapsed_hours', name: 'Elapsed time hours' },
		{ variableId: 'elapsed_minutes', name: 'Elapsed time minutes' },
		{ variableId: 'elapsed_seconds_component', name: 'Elapsed time seconds component' },
		{ variableId: 'progress_percent', name: 'Elapsed progress percent' },
		{ variableId: 'remaining_percent', name: 'Remaining percent' },
		{ variableId: 'additional_time_enabled', name: 'Additional time enabled' },
		{ variableId: 'additional_time_running', name: 'Additional time running' },
		{ variableId: 'additional_time_blink', name: 'Additional time blink enabled' },
		{ variableId: 'additional_time_seconds', name: 'Additional time in seconds' },
		{ variableId: 'additional_time_formatted', name: 'Additional time full formatted' },
		{ variableId: 'additional_time_hours', name: 'Additional time hours' },
		{ variableId: 'additional_time_minutes', name: 'Additional time minutes' },
		{ variableId: 'additional_time_seconds_component', name: 'Additional time seconds component' },
		{ variableId: 'message_text', name: 'Current message text' },
		{ variableId: 'message_color', name: 'Current message color' },
		{ variableId: 'message_blinking', name: 'Message blinking enabled' },
		{ variableId: 'clock_text', name: 'Current clock text' },
		{ variableId: 'clock_hours', name: 'Clock hours' },
		{ variableId: 'clock_minutes', name: 'Clock minutes' },
		{ variableId: 'clock_seconds', name: 'Clock seconds' },
		{ variableId: 'clock_ampm', name: 'Clock AM PM suffix' },
		{ variableId: 'chrono_seconds', name: 'Chrono time in seconds' },
		{ variableId: 'chrono_formatted', name: 'Chrono time formatted' },
		{ variableId: 'chrono_full_formatted', name: 'Chrono time full formatted' },
		{ variableId: 'chrono_blink_enabled', name: 'Chrono blink enabled' },
		{ variableId: 'chrono_blink_active', name: 'Chrono blink active state' },
		{ variableId: 'chrono_color_thresholds_enabled', name: 'Chrono color thresholds enabled' },
		{ variableId: 'chrono_threshold1', name: 'Chrono threshold 1 in seconds' },
		{ variableId: 'chrono_threshold1_color', name: 'Chrono threshold 1 color' },
		{ variableId: 'chrono_threshold2', name: 'Chrono threshold 2 in seconds' },
		{ variableId: 'chrono_threshold2_color', name: 'Chrono threshold 2 color' },
		{ variableId: 'chrono_hours', name: 'Chrono hours' },
		{ variableId: 'chrono_minutes', name: 'Chrono minutes' },
		{ variableId: 'chrono_seconds_component', name: 'Chrono seconds component' },
		{ variableId: 'red_alert_active', name: 'Red alert active' },
		{ variableId: 'red_alert_color', name: 'Red alert color' },
		{ variableId: 'audio_enabled', name: 'Audio enabled' },
		{ variableId: 'audio_master_volume_percent', name: 'Audio master volume percent' },
		{ variableId: 'audio_stop_current_on_play', name: 'Audio stop current on play' },
		{ variableId: 'audio_rule_count', name: 'Audio rule count' },
		{ variableId: 'audio_enabled_rule_count', name: 'Enabled audio rule count' },
		{ variableId: 'playlist_running', name: 'Playlist running' },
		{ variableId: 'playlist_intermission', name: 'Playlist intermission active' },
		{ variableId: 'playlist_session_count', name: 'Playlist session count' },
		{ variableId: 'playlist_enabled_session_count', name: 'Playlist enabled session count' },
		{ variableId: 'playlist_current_session_index', name: 'Current playlist session index' },
		{ variableId: 'playlist_current_session_name', name: 'Current playlist session name' },
		{ variableId: 'playlist_current_session_mode', name: 'Current playlist session mode' },
		{ variableId: 'playlist_current_session_enabled', name: 'Current playlist session enabled' },
		{ variableId: 'playlist_chrono_seconds', name: 'Playlist chrono in seconds' },
		{ variableId: 'playlist_chrono_formatted', name: 'Playlist chrono formatted' },
		{ variableId: 'playlist_chrono_hours', name: 'Playlist chrono hours' },
		{ variableId: 'playlist_chrono_minutes', name: 'Playlist chrono minutes' },
		{ variableId: 'playlist_chrono_seconds_component', name: 'Playlist chrono seconds component' },
	])
}
